[package]
name = "estimate_ml_fee"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tensorflow = "0.16.1" # tf 2.3.0, preprocessing need 2.4.0
tensorflow = {git="https://github.com/RCasatta/tensorflow-rust", branch="tensorflow_240"}
bitcoincore-rpc = "0.12.0"
structopt = "0.3.21"
env_logger = "0.8.2"
chrono = "0.4"
log = "0.4.13"
