[package]
name = "estimate_ml_fee"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = {git="https://github.com/RCasatta/tensorflow-rust", branch="tensorflow_240"}
#tensorflow = "0.16.1"
